# Generated by Django 3.2.25 on 2024-11-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsAndRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('one_star_rating', models.BooleanField(default=False)),
                ('two_star_rating', models.BooleanField(default=False)),
                ('three_star_rating', models.BooleanField(default=False)),
                ('four_star_rating', models.BooleanField(default=False)),
                ('five_star_rating', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True, max_length=600, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
