# Generated by Django 3.2.25 on 2024-11-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsandratings',
            options={'verbose_name_plural': 'Reviews and Ratings'},
        ),
    ]
