# Generated by Django 3.2.25 on 2024-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_visibilty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='visibilty',
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
